name: CD

on: 
  workflow_run: 
    workflows: [CI]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' 

      - name: Download Dependencies
        run: npm install
        working-directory: mywebsite

      - name: Run build
        run: npm run build
        working-directory: mywebsite

      - name: Setup git identity and deploy
        run: |
            git config --global user.email "xingruiricky@gmail.com"
            git config --global user.name "Xingrui Zhu"
            npx gh-pages -d build -t -r https://xingruiricky:${{ secrets.GITHUB_TOKEN }}@github.com/xingruiricky/xingruiwebsite.git
        working-directory: mywebsite
