name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v2

      - name: Download dependency
        run: npm install
        working-directory: mywebsite

      - name: Run tests
        run: npm test
        working-directory: mywebsite

  

